### PR TITLE
make the game engine

### PR DESCRIPTION
**Pull request by Elektriman**
This should cover everything regarding the computations for the planet generation, the shopping, the resource collection and the yaml configuration system

### CODE REVIEW

**Comment by FloncDev** [comment]
Make sure to run pre-commit on your end. Would also recommend installing pyright in your editor

**Comment by iauu** [comment]
The files should be in a subfolder of `api/src`, e.g. `api/src/core`

**Comment by Elektriman** [comment]
> Make sure to run pre-commit on your end. Would also recommend installing pyright in your editor

should we share a pyright config ? I'm trying to make it work without success

**Comment by FloncDev** [comment]
The pyright config should already be shared - it's configured in pyproject.toml

**Comment by MilaDog** [comment]
WIll have a check later on.

**Comment by MilaDog** [comment]
The structure seems good for now. Just will need to follow the `pre-commit`. Add doc strings to functions.

I assume the `...` in some functions is because it has not been implemented yet?

**Review by FloncDev — APPROVED** [review]

**Review by i-am-unknown-81514525 — APPROVED** [review]

**Pull request merged**
